Game logic
Alaska01/tic-tac-toe pull request #1
Opened 2020-08-28 19:07 UTC by Alaska01

Create the game logic for a tic-tac-toe game, with the game logic in the lib folder and the puts comments where in the main.rb file in the bin folder.

2020-08-28 22:05 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Alaska01, great job with this project :+1: The app works as expected, the code is clean :smile: Great job, before we get our project approved, let us address the comments below:

- Kindly enable linter checks for the repo. Currently, linter check is not working
- Update the executable file to use forward slash `/` instead of back slash `\`

KIndly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-08-28 22:05 UTC, addod19 commented on bin/main.rb
> +require_relative '..\lib\board'
Kindly replace `..\lib\board` with `../lib/board`, what we have currently gives a `loadError`. Let us fix it

2020-08-29 05:27 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes. You can merge it now :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-08-29 07:15 UTC, Alaska01 commented
Project approved, merging to go to the next milestone!!!!

2020-08-29 07:15 UTC, merged